# Autogenerated using ProtoBuf.jl v1.3.0
# original file: matrixserver/common/protobuf/matrixserver.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export var"ScreenData.Encoding", JoystickData, AppParamUpdate, Status
export var"ScreenInfo.ScreenOrientation", var"ScreenInfo.ScreenRotation", MessageType
export AudioData, AppParamDef, var"ServerConfig.AssemblyType"
export var"Connection.ConnectionType", ImuData, ScreenData, AppParamValues, ScreenInfo
export AppParamSchema, Connection, ServerConfig, MatrixServerMessage


@enumx var"ScreenData.Encoding" default=0 rgb24bbp=1

struct JoystickData
    joystickID::Int32
    axisX::Float32
    axisY::Float32
    buttonA::Bool
    buttonB::Bool
    buttonX::Bool
    buttonY::Bool
    buttonR::Bool
    buttonL::Bool
    buttonStart::Bool
    buttonSelect::Bool
    rightAxisX::Float32
    rightAxisY::Float32
    rightTrigger::Float32
    leftTrigger::Float32
    rightStickButton::Bool
    leftStickButton::Bool
    buttonDpadUp::Bool
    buttonDpadLeft::Bool
    buttonDpadDown::Bool
    buttonDpadRight::Bool
end
PB.default_values(::Type{JoystickData}) = (;joystickID = zero(Int32), axisX = zero(Float32), axisY = zero(Float32), buttonA = false, buttonB = false, buttonX = false, buttonY = false, buttonR = false, buttonL = false, buttonStart = false, buttonSelect = false, rightAxisX = zero(Float32), rightAxisY = zero(Float32), rightTrigger = zero(Float32), leftTrigger = zero(Float32), rightStickButton = false, leftStickButton = false, buttonDpadUp = false, buttonDpadLeft = false, buttonDpadDown = false, buttonDpadRight = false)
PB.field_numbers(::Type{JoystickData}) = (;joystickID = 1, axisX = 2, axisY = 3, buttonA = 4, buttonB = 5, buttonX = 6, buttonY = 7, buttonR = 8, buttonL = 9, buttonStart = 10, buttonSelect = 11, rightAxisX = 12, rightAxisY = 13, rightTrigger = 14, leftTrigger = 15, rightStickButton = 16, leftStickButton = 17, buttonDpadUp = 18, buttonDpadLeft = 19, buttonDpadDown = 20, buttonDpadRight = 21)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:JoystickData}, _endpos::Int=0, _group::Bool=false)
    joystickID = zero(Int32)
    axisX = zero(Float32)
    axisY = zero(Float32)
    buttonA = false
    buttonB = false
    buttonX = false
    buttonY = false
    buttonR = false
    buttonL = false
    buttonStart = false
    buttonSelect = false
    rightAxisX = zero(Float32)
    rightAxisY = zero(Float32)
    rightTrigger = zero(Float32)
    leftTrigger = zero(Float32)
    rightStickButton = false
    leftStickButton = false
    buttonDpadUp = false
    buttonDpadLeft = false
    buttonDpadDown = false
    buttonDpadRight = false
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            joystickID = PB.decode(d, Int32)
        elseif field_number == 2
            axisX = PB.decode(d, Float32)
        elseif field_number == 3
            axisY = PB.decode(d, Float32)
        elseif field_number == 4
            buttonA = PB.decode(d, Bool)
        elseif field_number == 5
            buttonB = PB.decode(d, Bool)
        elseif field_number == 6
            buttonX = PB.decode(d, Bool)
        elseif field_number == 7
            buttonY = PB.decode(d, Bool)
        elseif field_number == 8
            buttonR = PB.decode(d, Bool)
        elseif field_number == 9
            buttonL = PB.decode(d, Bool)
        elseif field_number == 10
            buttonStart = PB.decode(d, Bool)
        elseif field_number == 11
            buttonSelect = PB.decode(d, Bool)
        elseif field_number == 12
            rightAxisX = PB.decode(d, Float32)
        elseif field_number == 13
            rightAxisY = PB.decode(d, Float32)
        elseif field_number == 14
            rightTrigger = PB.decode(d, Float32)
        elseif field_number == 15
            leftTrigger = PB.decode(d, Float32)
        elseif field_number == 16
            rightStickButton = PB.decode(d, Bool)
        elseif field_number == 17
            leftStickButton = PB.decode(d, Bool)
        elseif field_number == 18
            buttonDpadUp = PB.decode(d, Bool)
        elseif field_number == 19
            buttonDpadLeft = PB.decode(d, Bool)
        elseif field_number == 20
            buttonDpadDown = PB.decode(d, Bool)
        elseif field_number == 21
            buttonDpadRight = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return JoystickData(joystickID, axisX, axisY, buttonA, buttonB, buttonX, buttonY, buttonR, buttonL, buttonStart, buttonSelect, rightAxisX, rightAxisY, rightTrigger, leftTrigger, rightStickButton, leftStickButton, buttonDpadUp, buttonDpadLeft, buttonDpadDown, buttonDpadRight)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::JoystickData)
    initpos = position(e.io)
    x.joystickID != zero(Int32) && PB.encode(e, 1, x.joystickID)
    x.axisX !== zero(Float32) && PB.encode(e, 2, x.axisX)
    x.axisY !== zero(Float32) && PB.encode(e, 3, x.axisY)
    x.buttonA != false && PB.encode(e, 4, x.buttonA)
    x.buttonB != false && PB.encode(e, 5, x.buttonB)
    x.buttonX != false && PB.encode(e, 6, x.buttonX)
    x.buttonY != false && PB.encode(e, 7, x.buttonY)
    x.buttonR != false && PB.encode(e, 8, x.buttonR)
    x.buttonL != false && PB.encode(e, 9, x.buttonL)
    x.buttonStart != false && PB.encode(e, 10, x.buttonStart)
    x.buttonSelect != false && PB.encode(e, 11, x.buttonSelect)
    x.rightAxisX !== zero(Float32) && PB.encode(e, 12, x.rightAxisX)
    x.rightAxisY !== zero(Float32) && PB.encode(e, 13, x.rightAxisY)
    x.rightTrigger !== zero(Float32) && PB.encode(e, 14, x.rightTrigger)
    x.leftTrigger !== zero(Float32) && PB.encode(e, 15, x.leftTrigger)
    x.rightStickButton != false && PB.encode(e, 16, x.rightStickButton)
    x.leftStickButton != false && PB.encode(e, 17, x.leftStickButton)
    x.buttonDpadUp != false && PB.encode(e, 18, x.buttonDpadUp)
    x.buttonDpadLeft != false && PB.encode(e, 19, x.buttonDpadLeft)
    x.buttonDpadDown != false && PB.encode(e, 20, x.buttonDpadDown)
    x.buttonDpadRight != false && PB.encode(e, 21, x.buttonDpadRight)
    return position(e.io) - initpos
end
function PB._encoded_size(x::JoystickData)
    encoded_size = 0
    x.joystickID != zero(Int32) && (encoded_size += PB._encoded_size(x.joystickID, 1))
    x.axisX !== zero(Float32) && (encoded_size += PB._encoded_size(x.axisX, 2))
    x.axisY !== zero(Float32) && (encoded_size += PB._encoded_size(x.axisY, 3))
    x.buttonA != false && (encoded_size += PB._encoded_size(x.buttonA, 4))
    x.buttonB != false && (encoded_size += PB._encoded_size(x.buttonB, 5))
    x.buttonX != false && (encoded_size += PB._encoded_size(x.buttonX, 6))
    x.buttonY != false && (encoded_size += PB._encoded_size(x.buttonY, 7))
    x.buttonR != false && (encoded_size += PB._encoded_size(x.buttonR, 8))
    x.buttonL != false && (encoded_size += PB._encoded_size(x.buttonL, 9))
    x.buttonStart != false && (encoded_size += PB._encoded_size(x.buttonStart, 10))
    x.buttonSelect != false && (encoded_size += PB._encoded_size(x.buttonSelect, 11))
    x.rightAxisX !== zero(Float32) && (encoded_size += PB._encoded_size(x.rightAxisX, 12))
    x.rightAxisY !== zero(Float32) && (encoded_size += PB._encoded_size(x.rightAxisY, 13))
    x.rightTrigger !== zero(Float32) && (encoded_size += PB._encoded_size(x.rightTrigger, 14))
    x.leftTrigger !== zero(Float32) && (encoded_size += PB._encoded_size(x.leftTrigger, 15))
    x.rightStickButton != false && (encoded_size += PB._encoded_size(x.rightStickButton, 16))
    x.leftStickButton != false && (encoded_size += PB._encoded_size(x.leftStickButton, 17))
    x.buttonDpadUp != false && (encoded_size += PB._encoded_size(x.buttonDpadUp, 18))
    x.buttonDpadLeft != false && (encoded_size += PB._encoded_size(x.buttonDpadLeft, 19))
    x.buttonDpadDown != false && (encoded_size += PB._encoded_size(x.buttonDpadDown, 20))
    x.buttonDpadRight != false && (encoded_size += PB._encoded_size(x.buttonDpadRight, 21))
    return encoded_size
end

struct AppParamUpdate
    key::String
    floatVal::Float32
    intVal::Int32
    boolVal::Bool
    stringVal::String
end
PB.default_values(::Type{AppParamUpdate}) = (;key = "", floatVal = zero(Float32), intVal = zero(Int32), boolVal = false, stringVal = "")
PB.field_numbers(::Type{AppParamUpdate}) = (;key = 1, floatVal = 2, intVal = 3, boolVal = 4, stringVal = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AppParamUpdate}, _endpos::Int=0, _group::Bool=false)
    key = ""
    floatVal = zero(Float32)
    intVal = zero(Int32)
    boolVal = false
    stringVal = ""
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            key = PB.decode(d, String)
        elseif field_number == 2
            floatVal = PB.decode(d, Float32)
        elseif field_number == 3
            intVal = PB.decode(d, Int32)
        elseif field_number == 4
            boolVal = PB.decode(d, Bool)
        elseif field_number == 5
            stringVal = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return AppParamUpdate(key, floatVal, intVal, boolVal, stringVal)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AppParamUpdate)
    initpos = position(e.io)
    !isempty(x.key) && PB.encode(e, 1, x.key)
    x.floatVal !== zero(Float32) && PB.encode(e, 2, x.floatVal)
    x.intVal != zero(Int32) && PB.encode(e, 3, x.intVal)
    x.boolVal != false && PB.encode(e, 4, x.boolVal)
    !isempty(x.stringVal) && PB.encode(e, 5, x.stringVal)
    return position(e.io) - initpos
end
function PB._encoded_size(x::AppParamUpdate)
    encoded_size = 0
    !isempty(x.key) && (encoded_size += PB._encoded_size(x.key, 1))
    x.floatVal !== zero(Float32) && (encoded_size += PB._encoded_size(x.floatVal, 2))
    x.intVal != zero(Int32) && (encoded_size += PB._encoded_size(x.intVal, 3))
    x.boolVal != false && (encoded_size += PB._encoded_size(x.boolVal, 4))
    !isempty(x.stringVal) && (encoded_size += PB._encoded_size(x.stringVal, 5))
    return encoded_size
end

@enumx Status defaultStatus=0 error=1 success=2 invalidRequest=3 requestDenied=4

@enumx var"ScreenInfo.ScreenOrientation" defaultScreenOrientation=0 front=1 right=2 back=3 left=4 top=5 bottom=6 anyScreen=10

@enumx var"ScreenInfo.ScreenRotation" rot0=0 rot90=1 rot180=2 rot270=3

@enumx MessageType defaultMessageType=0 registerApp=1 getServerInfo=2 requestScreenAccess=3 setScreenFrame=4 appAlive=5 appPause=6 appResume=7 appKill=8 imuData=9 joystickData=10 appParamSchema=11 setAppParam=12 getAppParams=13 appParamValues=14 audioDataMessage=15

struct AudioData
    volume::UInt32
    frequencyBands::Vector{UInt32}
end
PB.default_values(::Type{AudioData}) = (;volume = zero(UInt32), frequencyBands = Vector{UInt32}())
PB.field_numbers(::Type{AudioData}) = (;volume = 1, frequencyBands = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AudioData}, _endpos::Int=0, _group::Bool=false)
    volume = zero(UInt32)
    frequencyBands = PB.BufferedVector{UInt32}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            volume = PB.decode(d, UInt32)
        elseif field_number == 2
            PB.decode!(d, wire_type, frequencyBands)
        else
            Base.skip(d, wire_type)
        end
    end
    return AudioData(volume, frequencyBands[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AudioData)
    initpos = position(e.io)
    x.volume != zero(UInt32) && PB.encode(e, 1, x.volume)
    !isempty(x.frequencyBands) && PB.encode(e, 2, x.frequencyBands)
    return position(e.io) - initpos
end
function PB._encoded_size(x::AudioData)
    encoded_size = 0
    x.volume != zero(UInt32) && (encoded_size += PB._encoded_size(x.volume, 1))
    !isempty(x.frequencyBands) && (encoded_size += PB._encoded_size(x.frequencyBands, 2))
    return encoded_size
end

struct AppParamDef
    key::String
    label::String
    var"#type"::String
    minVal::Float32
    maxVal::Float32
    step::Float32
    defaultVal::Float32
    enumOptions::Vector{String}
    group::String
end
PB.default_values(::Type{AppParamDef}) = (;key = "", label = "", var"#type" = "", minVal = zero(Float32), maxVal = zero(Float32), step = zero(Float32), defaultVal = zero(Float32), enumOptions = Vector{String}(), group = "")
PB.field_numbers(::Type{AppParamDef}) = (;key = 1, label = 2, var"#type" = 3, minVal = 4, maxVal = 5, step = 6, defaultVal = 7, enumOptions = 8, group = 9)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AppParamDef}, _endpos::Int=0, _group::Bool=false)
    key = ""
    label = ""
    var"#type" = ""
    minVal = zero(Float32)
    maxVal = zero(Float32)
    step = zero(Float32)
    defaultVal = zero(Float32)
    enumOptions = PB.BufferedVector{String}()
    group = ""
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            key = PB.decode(d, String)
        elseif field_number == 2
            label = PB.decode(d, String)
        elseif field_number == 3
            var"#type" = PB.decode(d, String)
        elseif field_number == 4
            minVal = PB.decode(d, Float32)
        elseif field_number == 5
            maxVal = PB.decode(d, Float32)
        elseif field_number == 6
            step = PB.decode(d, Float32)
        elseif field_number == 7
            defaultVal = PB.decode(d, Float32)
        elseif field_number == 8
            PB.decode!(d, enumOptions)
        elseif field_number == 9
            group = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return AppParamDef(key, label, var"#type", minVal, maxVal, step, defaultVal, enumOptions[], group)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AppParamDef)
    initpos = position(e.io)
    !isempty(x.key) && PB.encode(e, 1, x.key)
    !isempty(x.label) && PB.encode(e, 2, x.label)
    !isempty(x.var"#type") && PB.encode(e, 3, x.var"#type")
    x.minVal !== zero(Float32) && PB.encode(e, 4, x.minVal)
    x.maxVal !== zero(Float32) && PB.encode(e, 5, x.maxVal)
    x.step !== zero(Float32) && PB.encode(e, 6, x.step)
    x.defaultVal !== zero(Float32) && PB.encode(e, 7, x.defaultVal)
    !isempty(x.enumOptions) && PB.encode(e, 8, x.enumOptions)
    !isempty(x.group) && PB.encode(e, 9, x.group)
    return position(e.io) - initpos
end
function PB._encoded_size(x::AppParamDef)
    encoded_size = 0
    !isempty(x.key) && (encoded_size += PB._encoded_size(x.key, 1))
    !isempty(x.label) && (encoded_size += PB._encoded_size(x.label, 2))
    !isempty(x.var"#type") && (encoded_size += PB._encoded_size(x.var"#type", 3))
    x.minVal !== zero(Float32) && (encoded_size += PB._encoded_size(x.minVal, 4))
    x.maxVal !== zero(Float32) && (encoded_size += PB._encoded_size(x.maxVal, 5))
    x.step !== zero(Float32) && (encoded_size += PB._encoded_size(x.step, 6))
    x.defaultVal !== zero(Float32) && (encoded_size += PB._encoded_size(x.defaultVal, 7))
    !isempty(x.enumOptions) && (encoded_size += PB._encoded_size(x.enumOptions, 8))
    !isempty(x.group) && (encoded_size += PB._encoded_size(x.group, 9))
    return encoded_size
end

@enumx var"ServerConfig.AssemblyType" defaultAssemblyType=0 flat=1 cube=2

@enumx var"Connection.ConnectionType" defaultConnectionType=0 tcp=1 udp=2

struct ImuData
    accelX::Float32
    accelY::Float32
    accelZ::Float32
    gyroX::Float32
    gyroY::Float32
    gyroZ::Float32
end
PB.default_values(::Type{ImuData}) = (;accelX = zero(Float32), accelY = zero(Float32), accelZ = zero(Float32), gyroX = zero(Float32), gyroY = zero(Float32), gyroZ = zero(Float32))
PB.field_numbers(::Type{ImuData}) = (;accelX = 1, accelY = 2, accelZ = 3, gyroX = 4, gyroY = 5, gyroZ = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ImuData}, _endpos::Int=0, _group::Bool=false)
    accelX = zero(Float32)
    accelY = zero(Float32)
    accelZ = zero(Float32)
    gyroX = zero(Float32)
    gyroY = zero(Float32)
    gyroZ = zero(Float32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            accelX = PB.decode(d, Float32)
        elseif field_number == 2
            accelY = PB.decode(d, Float32)
        elseif field_number == 3
            accelZ = PB.decode(d, Float32)
        elseif field_number == 4
            gyroX = PB.decode(d, Float32)
        elseif field_number == 5
            gyroY = PB.decode(d, Float32)
        elseif field_number == 6
            gyroZ = PB.decode(d, Float32)
        else
            Base.skip(d, wire_type)
        end
    end
    return ImuData(accelX, accelY, accelZ, gyroX, gyroY, gyroZ)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ImuData)
    initpos = position(e.io)
    x.accelX !== zero(Float32) && PB.encode(e, 1, x.accelX)
    x.accelY !== zero(Float32) && PB.encode(e, 2, x.accelY)
    x.accelZ !== zero(Float32) && PB.encode(e, 3, x.accelZ)
    x.gyroX !== zero(Float32) && PB.encode(e, 4, x.gyroX)
    x.gyroY !== zero(Float32) && PB.encode(e, 5, x.gyroY)
    x.gyroZ !== zero(Float32) && PB.encode(e, 6, x.gyroZ)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ImuData)
    encoded_size = 0
    x.accelX !== zero(Float32) && (encoded_size += PB._encoded_size(x.accelX, 1))
    x.accelY !== zero(Float32) && (encoded_size += PB._encoded_size(x.accelY, 2))
    x.accelZ !== zero(Float32) && (encoded_size += PB._encoded_size(x.accelZ, 3))
    x.gyroX !== zero(Float32) && (encoded_size += PB._encoded_size(x.gyroX, 4))
    x.gyroY !== zero(Float32) && (encoded_size += PB._encoded_size(x.gyroY, 5))
    x.gyroZ !== zero(Float32) && (encoded_size += PB._encoded_size(x.gyroZ, 6))
    return encoded_size
end

struct ScreenData
    screenID::Int32
    frameData::Vector{UInt8}
    encoding::var"ScreenData.Encoding".T
end
PB.default_values(::Type{ScreenData}) = (;screenID = zero(Int32), frameData = UInt8[], encoding = var"ScreenData.Encoding".default)
PB.field_numbers(::Type{ScreenData}) = (;screenID = 1, frameData = 2, encoding = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ScreenData}, _endpos::Int=0, _group::Bool=false)
    screenID = zero(Int32)
    frameData = UInt8[]
    encoding = var"ScreenData.Encoding".default
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            screenID = PB.decode(d, Int32)
        elseif field_number == 2
            frameData = PB.decode(d, Vector{UInt8})
        elseif field_number == 6
            encoding = PB.decode(d, var"ScreenData.Encoding".T)
        else
            Base.skip(d, wire_type)
        end
    end
    return ScreenData(screenID, frameData, encoding)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ScreenData)
    initpos = position(e.io)
    x.screenID != zero(Int32) && PB.encode(e, 1, x.screenID)
    !isempty(x.frameData) && PB.encode(e, 2, x.frameData)
    x.encoding != var"ScreenData.Encoding".default && PB.encode(e, 6, x.encoding)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ScreenData)
    encoded_size = 0
    x.screenID != zero(Int32) && (encoded_size += PB._encoded_size(x.screenID, 1))
    !isempty(x.frameData) && (encoded_size += PB._encoded_size(x.frameData, 2))
    x.encoding != var"ScreenData.Encoding".default && (encoded_size += PB._encoded_size(x.encoding, 6))
    return encoded_size
end

struct AppParamValues
    appName::String
    values::Vector{AppParamUpdate}
end
PB.default_values(::Type{AppParamValues}) = (;appName = "", values = Vector{AppParamUpdate}())
PB.field_numbers(::Type{AppParamValues}) = (;appName = 1, values = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AppParamValues}, _endpos::Int=0, _group::Bool=false)
    appName = ""
    values = PB.BufferedVector{AppParamUpdate}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            appName = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, values)
        else
            Base.skip(d, wire_type)
        end
    end
    return AppParamValues(appName, values[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AppParamValues)
    initpos = position(e.io)
    !isempty(x.appName) && PB.encode(e, 1, x.appName)
    !isempty(x.values) && PB.encode(e, 2, x.values)
    return position(e.io) - initpos
end
function PB._encoded_size(x::AppParamValues)
    encoded_size = 0
    !isempty(x.appName) && (encoded_size += PB._encoded_size(x.appName, 1))
    !isempty(x.values) && (encoded_size += PB._encoded_size(x.values, 2))
    return encoded_size
end

struct ScreenInfo
    screenID::Int32
    width::Int32
    height::Int32
    available::Bool
    screenOrientation::var"ScreenInfo.ScreenOrientation".T
    screenRotation::var"ScreenInfo.ScreenRotation".T
    offsetX::Int32
    offsetY::Int32
end
PB.default_values(::Type{ScreenInfo}) = (;screenID = zero(Int32), width = zero(Int32), height = zero(Int32), available = false, screenOrientation = var"ScreenInfo.ScreenOrientation".defaultScreenOrientation, screenRotation = var"ScreenInfo.ScreenRotation".rot0, offsetX = zero(Int32), offsetY = zero(Int32))
PB.field_numbers(::Type{ScreenInfo}) = (;screenID = 1, width = 2, height = 3, available = 4, screenOrientation = 5, screenRotation = 6, offsetX = 7, offsetY = 8)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ScreenInfo}, _endpos::Int=0, _group::Bool=false)
    screenID = zero(Int32)
    width = zero(Int32)
    height = zero(Int32)
    available = false
    screenOrientation = var"ScreenInfo.ScreenOrientation".defaultScreenOrientation
    screenRotation = var"ScreenInfo.ScreenRotation".rot0
    offsetX = zero(Int32)
    offsetY = zero(Int32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            screenID = PB.decode(d, Int32)
        elseif field_number == 2
            width = PB.decode(d, Int32)
        elseif field_number == 3
            height = PB.decode(d, Int32)
        elseif field_number == 4
            available = PB.decode(d, Bool)
        elseif field_number == 5
            screenOrientation = PB.decode(d, var"ScreenInfo.ScreenOrientation".T)
        elseif field_number == 6
            screenRotation = PB.decode(d, var"ScreenInfo.ScreenRotation".T)
        elseif field_number == 7
            offsetX = PB.decode(d, Int32)
        elseif field_number == 8
            offsetY = PB.decode(d, Int32)
        else
            Base.skip(d, wire_type)
        end
    end
    return ScreenInfo(screenID, width, height, available, screenOrientation, screenRotation, offsetX, offsetY)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ScreenInfo)
    initpos = position(e.io)
    x.screenID != zero(Int32) && PB.encode(e, 1, x.screenID)
    x.width != zero(Int32) && PB.encode(e, 2, x.width)
    x.height != zero(Int32) && PB.encode(e, 3, x.height)
    x.available != false && PB.encode(e, 4, x.available)
    x.screenOrientation != var"ScreenInfo.ScreenOrientation".defaultScreenOrientation && PB.encode(e, 5, x.screenOrientation)
    x.screenRotation != var"ScreenInfo.ScreenRotation".rot0 && PB.encode(e, 6, x.screenRotation)
    x.offsetX != zero(Int32) && PB.encode(e, 7, x.offsetX)
    x.offsetY != zero(Int32) && PB.encode(e, 8, x.offsetY)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ScreenInfo)
    encoded_size = 0
    x.screenID != zero(Int32) && (encoded_size += PB._encoded_size(x.screenID, 1))
    x.width != zero(Int32) && (encoded_size += PB._encoded_size(x.width, 2))
    x.height != zero(Int32) && (encoded_size += PB._encoded_size(x.height, 3))
    x.available != false && (encoded_size += PB._encoded_size(x.available, 4))
    x.screenOrientation != var"ScreenInfo.ScreenOrientation".defaultScreenOrientation && (encoded_size += PB._encoded_size(x.screenOrientation, 5))
    x.screenRotation != var"ScreenInfo.ScreenRotation".rot0 && (encoded_size += PB._encoded_size(x.screenRotation, 6))
    x.offsetX != zero(Int32) && (encoded_size += PB._encoded_size(x.offsetX, 7))
    x.offsetY != zero(Int32) && (encoded_size += PB._encoded_size(x.offsetY, 8))
    return encoded_size
end

struct AppParamSchema
    appName::String
    params::Vector{AppParamDef}
end
PB.default_values(::Type{AppParamSchema}) = (;appName = "", params = Vector{AppParamDef}())
PB.field_numbers(::Type{AppParamSchema}) = (;appName = 1, params = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AppParamSchema}, _endpos::Int=0, _group::Bool=false)
    appName = ""
    params = PB.BufferedVector{AppParamDef}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            appName = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, params)
        else
            Base.skip(d, wire_type)
        end
    end
    return AppParamSchema(appName, params[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AppParamSchema)
    initpos = position(e.io)
    !isempty(x.appName) && PB.encode(e, 1, x.appName)
    !isempty(x.params) && PB.encode(e, 2, x.params)
    return position(e.io) - initpos
end
function PB._encoded_size(x::AppParamSchema)
    encoded_size = 0
    !isempty(x.appName) && (encoded_size += PB._encoded_size(x.appName, 1))
    !isempty(x.params) && (encoded_size += PB._encoded_size(x.params, 2))
    return encoded_size
end

struct Connection
    serverAddress::String
    serverPort::String
    connectionType::var"Connection.ConnectionType".T
end
PB.default_values(::Type{Connection}) = (;serverAddress = "", serverPort = "", connectionType = var"Connection.ConnectionType".defaultConnectionType)
PB.field_numbers(::Type{Connection}) = (;serverAddress = 1, serverPort = 2, connectionType = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Connection}, _endpos::Int=0, _group::Bool=false)
    serverAddress = ""
    serverPort = ""
    connectionType = var"Connection.ConnectionType".defaultConnectionType
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            serverAddress = PB.decode(d, String)
        elseif field_number == 2
            serverPort = PB.decode(d, String)
        elseif field_number == 3
            connectionType = PB.decode(d, var"Connection.ConnectionType".T)
        else
            Base.skip(d, wire_type)
        end
    end
    return Connection(serverAddress, serverPort, connectionType)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Connection)
    initpos = position(e.io)
    !isempty(x.serverAddress) && PB.encode(e, 1, x.serverAddress)
    !isempty(x.serverPort) && PB.encode(e, 2, x.serverPort)
    x.connectionType != var"Connection.ConnectionType".defaultConnectionType && PB.encode(e, 3, x.connectionType)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Connection)
    encoded_size = 0
    !isempty(x.serverAddress) && (encoded_size += PB._encoded_size(x.serverAddress, 1))
    !isempty(x.serverPort) && (encoded_size += PB._encoded_size(x.serverPort, 2))
    x.connectionType != var"Connection.ConnectionType".defaultConnectionType && (encoded_size += PB._encoded_size(x.connectionType, 3))
    return encoded_size
end

struct ServerConfig
    screenInfo::Vector{ScreenInfo}
    assemblyType::var"ServerConfig.AssemblyType".T
    globalScreenBrightness::Int32
    serverConnection::Union{Nothing,Connection}
    serverName::String
    simulatorAddress::String
    simulatorPort::String
end
PB.default_values(::Type{ServerConfig}) = (;screenInfo = Vector{ScreenInfo}(), assemblyType = var"ServerConfig.AssemblyType".defaultAssemblyType, globalScreenBrightness = zero(Int32), serverConnection = nothing, serverName = "", simulatorAddress = "", simulatorPort = "")
PB.field_numbers(::Type{ServerConfig}) = (;screenInfo = 1, assemblyType = 2, globalScreenBrightness = 3, serverConnection = 4, serverName = 5, simulatorAddress = 6, simulatorPort = 7)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ServerConfig}, _endpos::Int=0, _group::Bool=false)
    screenInfo = PB.BufferedVector{ScreenInfo}()
    assemblyType = var"ServerConfig.AssemblyType".defaultAssemblyType
    globalScreenBrightness = zero(Int32)
    serverConnection = Ref{Union{Nothing,Connection}}(nothing)
    serverName = ""
    simulatorAddress = ""
    simulatorPort = ""
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, screenInfo)
        elseif field_number == 2
            assemblyType = PB.decode(d, var"ServerConfig.AssemblyType".T)
        elseif field_number == 3
            globalScreenBrightness = PB.decode(d, Int32)
        elseif field_number == 4
            PB.decode!(d, serverConnection)
        elseif field_number == 5
            serverName = PB.decode(d, String)
        elseif field_number == 6
            simulatorAddress = PB.decode(d, String)
        elseif field_number == 7
            simulatorPort = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return ServerConfig(screenInfo[], assemblyType, globalScreenBrightness, serverConnection[], serverName, simulatorAddress, simulatorPort)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ServerConfig)
    initpos = position(e.io)
    !isempty(x.screenInfo) && PB.encode(e, 1, x.screenInfo)
    x.assemblyType != var"ServerConfig.AssemblyType".defaultAssemblyType && PB.encode(e, 2, x.assemblyType)
    x.globalScreenBrightness != zero(Int32) && PB.encode(e, 3, x.globalScreenBrightness)
    !isnothing(x.serverConnection) && PB.encode(e, 4, x.serverConnection)
    !isempty(x.serverName) && PB.encode(e, 5, x.serverName)
    !isempty(x.simulatorAddress) && PB.encode(e, 6, x.simulatorAddress)
    !isempty(x.simulatorPort) && PB.encode(e, 7, x.simulatorPort)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ServerConfig)
    encoded_size = 0
    !isempty(x.screenInfo) && (encoded_size += PB._encoded_size(x.screenInfo, 1))
    x.assemblyType != var"ServerConfig.AssemblyType".defaultAssemblyType && (encoded_size += PB._encoded_size(x.assemblyType, 2))
    x.globalScreenBrightness != zero(Int32) && (encoded_size += PB._encoded_size(x.globalScreenBrightness, 3))
    !isnothing(x.serverConnection) && (encoded_size += PB._encoded_size(x.serverConnection, 4))
    !isempty(x.serverName) && (encoded_size += PB._encoded_size(x.serverName, 5))
    !isempty(x.simulatorAddress) && (encoded_size += PB._encoded_size(x.simulatorAddress, 6))
    !isempty(x.simulatorPort) && (encoded_size += PB._encoded_size(x.simulatorPort, 7))
    return encoded_size
end

struct MatrixServerMessage
    messageType::MessageType.T
    appID::Int32
    status::Status.T
    screenData::Vector{ScreenData}
    joystickData::Vector{JoystickData}
    imuData::Union{Nothing,ImuData}
    serverConfig::Union{Nothing,ServerConfig}
    appParamSchema::Union{Nothing,AppParamSchema}
    appParamUpdate::Union{Nothing,AppParamUpdate}
    appParamValues::Union{Nothing,AppParamValues}
    audioData::Union{Nothing,AudioData}
end
PB.default_values(::Type{MatrixServerMessage}) = (;messageType = MessageType.defaultMessageType, appID = zero(Int32), status = Status.defaultStatus, screenData = Vector{ScreenData}(), joystickData = Vector{JoystickData}(), imuData = nothing, serverConfig = nothing, appParamSchema = nothing, appParamUpdate = nothing, appParamValues = nothing, audioData = nothing)
PB.field_numbers(::Type{MatrixServerMessage}) = (;messageType = 1, appID = 2, status = 3, screenData = 4, joystickData = 5, imuData = 6, serverConfig = 10, appParamSchema = 15, appParamUpdate = 16, appParamValues = 17, audioData = 18)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MatrixServerMessage}, _endpos::Int=0, _group::Bool=false)
    messageType = MessageType.defaultMessageType
    appID = zero(Int32)
    status = Status.defaultStatus
    screenData = PB.BufferedVector{ScreenData}()
    joystickData = PB.BufferedVector{JoystickData}()
    imuData = Ref{Union{Nothing,ImuData}}(nothing)
    serverConfig = Ref{Union{Nothing,ServerConfig}}(nothing)
    appParamSchema = Ref{Union{Nothing,AppParamSchema}}(nothing)
    appParamUpdate = Ref{Union{Nothing,AppParamUpdate}}(nothing)
    appParamValues = Ref{Union{Nothing,AppParamValues}}(nothing)
    audioData = Ref{Union{Nothing,AudioData}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            messageType = PB.decode(d, MessageType.T)
        elseif field_number == 2
            appID = PB.decode(d, Int32)
        elseif field_number == 3
            status = PB.decode(d, Status.T)
        elseif field_number == 4
            PB.decode!(d, screenData)
        elseif field_number == 5
            PB.decode!(d, joystickData)
        elseif field_number == 6
            PB.decode!(d, imuData)
        elseif field_number == 10
            PB.decode!(d, serverConfig)
        elseif field_number == 15
            PB.decode!(d, appParamSchema)
        elseif field_number == 16
            PB.decode!(d, appParamUpdate)
        elseif field_number == 17
            PB.decode!(d, appParamValues)
        elseif field_number == 18
            PB.decode!(d, audioData)
        else
            Base.skip(d, wire_type)
        end
    end
    return MatrixServerMessage(messageType, appID, status, screenData[], joystickData[], imuData[], serverConfig[], appParamSchema[], appParamUpdate[], appParamValues[], audioData[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MatrixServerMessage)
    initpos = position(e.io)
    x.messageType != MessageType.defaultMessageType && PB.encode(e, 1, x.messageType)
    x.appID != zero(Int32) && PB.encode(e, 2, x.appID)
    x.status != Status.defaultStatus && PB.encode(e, 3, x.status)
    !isempty(x.screenData) && PB.encode(e, 4, x.screenData)
    !isempty(x.joystickData) && PB.encode(e, 5, x.joystickData)
    !isnothing(x.imuData) && PB.encode(e, 6, x.imuData)
    !isnothing(x.serverConfig) && PB.encode(e, 10, x.serverConfig)
    !isnothing(x.appParamSchema) && PB.encode(e, 15, x.appParamSchema)
    !isnothing(x.appParamUpdate) && PB.encode(e, 16, x.appParamUpdate)
    !isnothing(x.appParamValues) && PB.encode(e, 17, x.appParamValues)
    !isnothing(x.audioData) && PB.encode(e, 18, x.audioData)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MatrixServerMessage)
    encoded_size = 0
    x.messageType != MessageType.defaultMessageType && (encoded_size += PB._encoded_size(x.messageType, 1))
    x.appID != zero(Int32) && (encoded_size += PB._encoded_size(x.appID, 2))
    x.status != Status.defaultStatus && (encoded_size += PB._encoded_size(x.status, 3))
    !isempty(x.screenData) && (encoded_size += PB._encoded_size(x.screenData, 4))
    !isempty(x.joystickData) && (encoded_size += PB._encoded_size(x.joystickData, 5))
    !isnothing(x.imuData) && (encoded_size += PB._encoded_size(x.imuData, 6))
    !isnothing(x.serverConfig) && (encoded_size += PB._encoded_size(x.serverConfig, 10))
    !isnothing(x.appParamSchema) && (encoded_size += PB._encoded_size(x.appParamSchema, 15))
    !isnothing(x.appParamUpdate) && (encoded_size += PB._encoded_size(x.appParamUpdate, 16))
    !isnothing(x.appParamValues) && (encoded_size += PB._encoded_size(x.appParamValues, 17))
    !isnothing(x.audioData) && (encoded_size += PB._encoded_size(x.audioData, 18))
    return encoded_size
end
